# Generated by Django 5.2.2 on 2025-06-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='image',
            field=models.ImageField(default=1, height_field=100, upload_to='', width_field=75),
            preserve_default=False,
        ),
    ]
