# Generated by Django 5.2.2 on 2025-06-09 12:23

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_wiki_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='contents',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
